from . import postlogistics_carrier_template_options
from . import delivery_carrier
from . import product_packaging
from . import postlogistics_license
from . import postlogistics_shipping_label
from . import stock_picking
from . import stock_quant_package
from . import stock_move
from . import res_partner
