
-
  Warehouse config
-
  !python {model: stock.config.settings}: |
    config_obj = self.pool.get('stock.config.settings')
    if config_obj:
        vals = {
            'group_stock_tracking_lot': 'True',
        }
        config_id = config_obj.create(cr, uid, vals, context)
        config = config_obj.browse(cr, uid, config_id)
        config.execute()
