[project]
name = "odoo-addons-oca-delivery-carrier"
version = "18.0.20250520.1"
dependencies = [
    "odoo-addon-delivery_carrier_account==18.0.*",
    "odoo-addon-delivery_carrier_info==18.0.*",
    "odoo-addon-delivery_carrier_label_default==18.0.*",
    "odoo-addon-delivery_carrier_manual_price==18.0.*",
    "odoo-addon-delivery_carrier_manual_weight==18.0.*",
    "odoo-addon-delivery_carrier_option==18.0.*",
    "odoo-addon-delivery_carrier_partner==18.0.*",
    "odoo-addon-delivery_carrier_pricelist==18.0.*",
    "odoo-addon-delivery_carrier_shipping_label==18.0.*",
    "odoo-addon-delivery_carrier_warehouse==18.0.*",
    "odoo-addon-delivery_free_fee_removal==18.0.*",
    "odoo-addon-delivery_package_fee==18.0.*",
    "odoo-addon-delivery_package_number==18.0.*",
    "odoo-addon-delivery_postlogistics==18.0.*",
    "odoo-addon-delivery_postlogistics_dangerous_goods==18.0.*",
    "odoo-addon-delivery_postlogistics_server_env==18.0.*",
    "odoo-addon-delivery_price_method==18.0.*",
    "odoo-addon-delivery_roulier==18.0.*",
    "odoo-addon-delivery_state==18.0.*",
    "odoo-addon-partner_delivery_info==18.0.*",
    "odoo-addon-partner_delivery_schedule==18.0.*",
    "odoo-addon-server_environment_delivery==18.0.*",
    "odoo-addon-stock_picking_carrier_from_rule==18.0.*",
    "odoo-addon-stock_picking_delivery_link==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
