[project]
name = "odoo-addons-oca-delivery-carrier"
version = "19.0.20260501.3"
dependencies = [
    "odoo-addon-delivery_carrier_account==19.0.*",
    "odoo-addon-delivery_carrier_agency==19.0.*",
    "odoo-addon-delivery_carrier_manual_price==19.0.*",
    "odoo-addon-delivery_carrier_option==19.0.*",
    "odoo-addon-delivery_carrier_partner==19.0.*",
    "odoo-addon-delivery_carrier_picking_valid==19.0.*",
    "odoo-addon-delivery_carrier_picking_valid_dangerous_goods==19.0.*",
    "odoo-addon-delivery_correos_express==19.0.*",
    "odoo-addon-delivery_multi_destination==19.0.*",
    "odoo-addon-delivery_package_number==19.0.*",
    "odoo-addon-delivery_price_method==19.0.*",
    "odoo-addon-delivery_state==19.0.*",
    "odoo-addon-partner_delivery_info==19.0.*",
    "odoo-addon-partner_delivery_zone==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
