# Copyright 2025 Tecnativa - Víctor Martínez
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

# Master Data provided by Dachser

DACHSER_PRODUCTS_T = [
    ("Z", "(Z) targospeed"),
    ("S", "(S) targospeed 10"),
    ("E", "(E) targospeed 12"),
    ("X", "(X) targospeed plus"),
    ("V", "(V) targofix"),
    ("R", "(R) targofix 10"),
    ("W", "(W) targofix 12"),
    ("Y", "(Y) targoflex"),
    ("A", "(A) targo on-site *"),
    ("B", "(B) targo on-site plus *"),
    ("H", "(H) targo on-site premium"),
    ("N", "(N) classicline"),
    ("U", "(U) targo on-site fix **"),
]
DACHSER_PRODUCTS_F = [
    ("E", "(E) vengospeed"),
    ("S", "(S) vengospeed 11"),
    ("N", "(N) vengoflex"),
    ("K", "(K) vengoflex"),
    ("Q", "(Q) vengofix"),
    ("X", "(X) vengospeed plus"),
    ("I", "(I) weekend service"),
    ("L", "(L) weekend service 11"),
]
DACHSER_TERMS = [
    ("011", "(011) Ex works"),
    ("031", "(031) Free delivered"),
    ("035", "(035) Ex works including delivery against invoice "),
    ("041", "(041) Free border; uncleared excluding duty & tax"),
    ("081", "(081) Free delivered; uncleared excluding duty & tax"),
    ("082", "(082) Free delivered; cleared excluding duty & tax"),
    ("083", "(083) Free delivered; cleared including duty, excluding tax"),
    ("084", "(084) Free delivered; cleared including duty & tax"),
    ("085", "(085) Free delivered; insured, uncleared, excluding duty & tax"),
    ("995", "(995) Service goods, insured; only by arrangement with the consolidator"),
]
DACHSER_PACKAGING_T = [
    ("LP", "(LP) large packaging"),
    ("DG", "(DG) pressure receptacle"),
    ("GE", "(GE) receptacle"),
    ("S", "(S) Bag"),
    ("BL", "(BL) Bale"),
    ("BR", "(BR) Barrel"),
    ("PT", "(PT) Batch"),
    ("BB", "(BB) Big Bag"),
    ("FL", "(FL) Bottle"),
    ("BX", "(BX) Box"),
    ("E", "(E) Bucket"),
    ("B", "(B) Bundle"),
    ("KT", "(KT) Carton"),
    ("RO", "(RO) Castor"),
    ("C2", "(C2) Chep-Half-Pallet"),
    ("C0", "(C0) Chep-Industrial Pallet 1,2x1m"),
    ("C4", "(C4) Chep-Quarter-Pallet"),
    ("C1", "(C1) Chep-Standard-Pallet"),
    ("CC", "(CC) Collapsable Stillage"),
    ("CT", "(CT) Container"),
    ("CR", "(CR) Crate"),
    ("KH", "(KH) Customer Sterile Pallet"),
    ("ZK", "(ZK) Customs envelope"),
    ("DI", "(D) Display"),
    ("EW", "(EW) Disposable Pallet"),
    ("F", "(F) Drum"),
    ("DD", "(DD) Düsseldorfer pallet"),
    ("M1", "(M1) Euro container 150mm"),
    ("M2", "(M2) Euro container 220mm"),
    ("M3", "(M3) Euro container 300mm"),
    ("EU", "(EU) Euro Pallet"),
    ("E2", "(E2) Euro-Meat-Tray 2"),
    ("AR", "(AR) Frame"),
    ("HE", "(HE) Half EU pallet"),
    ("IP", "(IP) Industrial Pallet"),
    ("IB", "(IB) Intermediate bulk container"),
    ("I1", "(I1) IPP Euro pallet"),
    ("I2", "(I2) I2 IPP half pallet"),
    ("I4", "(I4) I4 IPP quarter pallet"),
    ("KN", "(KN) Jerrican"),
    ("FB", "(FB) Light gauge metal packaging"),
    ("PA", "(PA) Parcel/Packet"),
    ("ST", "(ST) Piece"),
    ("KK", "(KK) Plastic jerrican"),
    ("KD", "(KD) Plastic DD pal (customer own)"),
    ("PH", "(PH) Privately-owned Container"),
    ("SD", "(SD) Protection lid"),
    ("VE", "(VE) Quarter EU-pallet"),
    ("G", "(G) Rack"),
    ("RL", "(RL) Roll"),
    ("RC", "(RC) Roll&GOH"),
    ("VG", "(VG) Security cage"),
    ("GB", "(GB) Skeleton box pallet"),
    ("TR", "(TR) Spool"),
    ("H1", "(H1) Sterile Pallet 1"),
]
DACHSER_PACKAGING_F = [
    ("BL", "(BL) Bale"),
    ("PT", "(PT) Batch"),
    ("BB", "(BB) Big Bag"),
    ("FL", "(FL) Bottle"),
    ("BX", "(BX) Box"),
    ("E", "(E) Bucket"),
    ("KT", "(KT) Carton"),
    ("RO", "(RO) Castor"),
    ("C2", "(C2) Chep-Half-Pallet"),
    ("C4", "(C4) Chep-Quarter-Pallet"),
    ("C1", "(C1) Chep-Standard-Pallet"),
    ("CC", "(CC) Collapsable Stillage"),
    ("CT", "(CT) Container"),
    ("KE", "(KE) Customer Euro- Meat Tray 2"),
    ("KH", "(KH) Customer Sterile Pallet"),
    ("DI", "(DI) Display"),
    ("EW", "(EW) Disposable Pallet"),
    ("F", "(F) Drum"),
    ("DD", "(DD) Düsseldorfer pallet"),
    ("B1", "(B1) E-performance case 1"),
    ("B2", "(B2) E-performance case 2"),
    ("B3", "(B3) E-performance case 3"),
    ("M1", "(M1) Euro container 150mm"),
    ("M2", "(M2) Euro container 220mm"),
    ("M3", "(M3) Euro container 300mm"),
    ("EU", "(EU) Euro Pallet"),
    ("E1", "(E1) Euro-Meat-Tray 1"),
    ("E2", "(E2) Euro-Meat-Tray 2"),
    ("E4", "(E4) Euro-Meat-Tray 4"),
    ("IP", "(IP) Industrial Pallet"),
    ("IB", "(IB) Intermediate bulk container"),
    ("I1", "(I1) IPP Euro pallet"),
    ("I2", "(I2) I2 IPP half pallet"),
    ("I4", "(I4) I4 IPP quarter pallet"),
    ("P4", "(P4) Paki 1.4"),
    ("PA", "(PA) Parcel/Packet"),
    ("ST", "(ST) Piece"),
    ("KK", "(KK) Plastic jerrican"),
    ("KD", "(KD) Plastic DD pal (customer own)"),
    ("PH", "(PH) Privately-owned Container"),
    ("RC", "(RC) Roll&GOH"),
    ("VG", "(VG) Security cage"),
    ("GB", "(GB) Skeleton box pallet"),
    ("H1", "(H1) Sterile Pallet 1"),
]

DACHSER_SHIPMENT_STATUS = {
    # unloading
    "E": "shipping_recorded_in_carrier",
    # loading
    "A": "shipping_recorded_in_carrier",
    # on delivery
    "R": "in_transit",
    # delivery differences
    "K": "incident",
    # delivery
    "Z": "customer_delivered",
}
